### ISSUE TITLE
 Animation transition between pages

### ISSUE THREAD

**Issue by Uriah1989** [zeroCoder1/Epub-Reader#3]
Good day. Is it possible to change the animation transition between pages, and not sections? Can you help? Sorry for my english. Great thanks!

**Comment by umair-interface** [comment]
@zeroCoder1 , my requirement is the same as discussed above,
i want to divide every chapter into pages..please send me the code at umair2071@ymail.com.
i will be very thankful to you @zeroCoder1

**Comment by zeroCoder1** [comment]
I have explained the logic on top. I will try and be more clear. I cannot send the entire code due to various reasons, I am no longer actively maintaining the repository, although I will fix most of the things.
You can divide the pages based on the height of the device, and the CSS will create the pagination in a scrollview.
index0 idx1    idx2    idx3
0000  0000   0000   0000
0000  0000   0000   0000
0000  0000   0000   0000
so now on every swipe you increment the index of that particular chapter, you will easily get the count, by measuring the width of the device. So total count = webview.scrollview.contentSize/widthOfTheDevice
Now increment it till you are == to the total count. 
There you have your pagination logic. 
Hope it helps.
